services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - APP_URL=https://docs.jjcasa.net
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER={{team.BOOKSTACK_DB_USER}}
      - DB_PASS={{team.BOOKSTACK_DB_PASS}}
      - DB_DATABASE=bookstackapp
    volumes:
      - /path/to/bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD={{team.BOOKSTACK_DB_ROOTPASS}}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER={{team.BOOKSTACK_DB_USER}}
      - MYSQL_PASSWORD={{team.BOOKSTACK_DB_PASS}}
    volumes:
      - /path/to/bookstack_db_data:/config
    restart: unless-stopped
